- name: Terraform
  hosts: localhost
  tasks:
    - name: Initialize Terraform
      command: terraform init
      args:
        chdir: /home/ubuntu/project/development-enviornment/Terraform

    - name: Apply Terraform Configuration
      command: terraform apply -auto-approve
      args:
        chdir: /home/ubuntu/project/development-enviornment/Terraform